development:
  nextflowpath: "/home/vagrant/"
  nextflowscript: "/home/vagrant/annot-nf/annot.nf"
  locationconfig: "/home/vagrant/annot-nf/loc_docker.config"
  extrinsicconfig: "/home/vagrant/annot-nf/data/augustus/extrinsic.cfg"
#  referencedir: "/Users/ss34/rails/testapp/references"
  referencedir: "/home/vagrant/annot-nf/example-data/references"
  dockerconf: "-with-docker satta/annot-nf"
  rootdir: "/home/vagrant/annot-nf/"
  workdir: "/home/vagrant/work"
  tmpdir: "/tmp"

production:
  nextflowpath: "/Users/ss34/"
  nextflowscript: "/Users/ss34/develop/annot-nf/annot.nf"
  locationconfig: "/Users/ss34/develop/annot-nf/loc_docker.config"
  extrinsicconfig: "/Users/ss34/develop/annot-nf/data/augustus/extrinsic.cfg"
  referencedir: "/Users/ss34/rails/testapp/references"
  dockerconf: "-with-docker satta/annot-nf"
  rootdir: "/Users/ss34/develop/annot-nf/"
  workdir: "/Users/ss34/develop/annot-nf/work"
  tmpdir: "/tmp"

test:
  nextflowpath: "/Users/ss34/"
  nextflowscript: "/Users/ss34/develop/annot-nf/annot.nf"
  locationconfig: "/Users/ss34/develop/annot-nf/loc_docker.config"
  extrinsicconfig: "/Users/ss34/develop/annot-nf/data/augustus/extrinsic.cfg"
  referencedir: "/Users/ss34/rails/testapp/references"
  dockerconf: "-with-docker satta/annot-nf"
  rootdir: "/Users/ss34/develop/annot-nf/"
  workdir: "/Users/ss34/develop/annot-nf/work"
  tmpdir: "/tmp"
